import OpenAI from 'openai';
import { config } from './config';
import { RepoData, AnalysisResult, ImprovementSuggestion } from './types';

export class LLMService {
  private openai: OpenAI;

  constructor() {
    this.openai = new OpenAI({
      apiKey: config.openai.apiKey,
    });
  }

  /**
   * Analyze repository and generate improvement suggestions
   */
  async analyzeRepository(repoData: RepoData): Promise<AnalysisResult> {
    const prompt = this.buildAnalysisPrompt(repoData);

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4-turbo-preview',
        messages: [
          {
            role: 'system',
            content: `You are a helpful software engineering assistant that analyzes GitHub repositories and provides concrete, actionable improvement suggestions.

Focus on:
- Code quality and maintainability
- Testing and CI/CD
- Documentation
- Security best practices
- Dependency management
- Performance optimizations

Return your response as a valid JSON object with this structure:
{
  "summary": "A 2-3 sentence overview of the repository's health",
  "healthScore": 75,
  "suggestions": [
    {
      "title": "Add comprehensive test coverage",
      "description": "Detailed explanation of the suggestion",
      "priority": "high",
      "category": "testing",
      "issueBody": "Markdown-formatted body for a GitHub issue"
    }
  ]
}`,
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.7,
        response_format: { type: 'json_object' },
      });

      const content = response.choices[0].message.content;
      if (!content) {
        throw new Error('No content in OpenAI response');
      }

      const result = JSON.parse(content) as AnalysisResult;

      // Ensure suggestions have required fields
      result.suggestions = result.suggestions.map((suggestion) => ({
        ...suggestion,
        issueBody: suggestion.issueBody || this.generateIssueBody(suggestion),
      }));

      return result;
    } catch (error) {
      console.error('Error analyzing repository with LLM:', error);
      throw error;
    }
  }

  /**
   * Build the analysis prompt from repository data
   */
  private buildAnalysisPrompt(repoData: RepoData): string {
    const languagesStr = Object.entries(repoData.languages)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([lang, bytes]) => `${lang} (${bytes} bytes)`)
      .join(', ');

    return `Analyze this GitHub repository and provide exactly 3 concrete improvement suggestions:

Repository: ${repoData.fullName}
Description: ${repoData.description || 'No description'}
Primary Language: ${repoData.language || 'Unknown'}
Languages: ${languagesStr || 'None detected'}
Stars: ${repoData.stargazersCount}
Forks: ${repoData.forksCount}
Open Issues: ${repoData.openIssuesCount}
Last Commit: ${repoData.lastCommitDate || 'Unknown'}
Has Tests: ${repoData.hasTests ? 'Yes' : 'No'}
Has CI/CD: ${repoData.hasCICD ? 'Yes' : 'No'}
Topics: ${repoData.topics.join(', ') || 'None'}

Please provide:
1. A brief summary of the repository's overall health
2. A health score from 0-100
3. Exactly 3 specific, actionable improvement suggestions with:
   - Clear title
   - Detailed description
   - Priority level (low/medium/high)
   - Category (testing, documentation, security, performance, dependencies, ci-cd, code-quality)
   - A well-formatted GitHub issue body in Markdown

Focus on the most impactful improvements based on the data above.`;
  }

  /**
   * Generate a GitHub issue body from a suggestion
   */
  private generateIssueBody(suggestion: ImprovementSuggestion): string {
    return `## Description

${suggestion.description}

## Priority

${suggestion.priority.charAt(0).toUpperCase() + suggestion.priority.slice(1)}

## Category

${suggestion.category}

---

*This issue was automatically generated by the Self-Optimization Orchestrator*
`;
  }
}
